<a href="https://colab.research.google.com/github/SamriddhiKhaanduri08/SamriddhiKhaanduri08.github.io/blob/main/AmericanExpressDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **American Express Data Analysis **

  IMPORTING LIBRARIES

In [19]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [20]:
tf.__version__

'2.13.0'

IMPORTING DATASET


In [21]:
dataset = pd.read_csv('Book1.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [22]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


Encoding Catergorical Data

Gender Column: Label Encoding

In [23]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [24]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


Geography column: One hot Encoding

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [26]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


Splitting dataset into Training & Test set

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling


In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ANN

Initialization

In [29]:
ann = tf.keras.models.Sequential()

Adding imput layer and first hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

Adding second hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units = 5, activation = 'relu'))

Adding output layer

In [50]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

ann.add(tf.keras.layers.Dense(units = 5, activation = 'sigmoid'))


ANN Training


Compiling ANN

In [51]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training on training dataset

In [52]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 1s 2ms/step - loss: 0.8019 - accuracy: 0.3361
Epoch 2/120
249/249 [==============================] - 0s 2ms/step - loss: 0.5705 - accuracy: 0.7966
Epoch 3/120
249/249 [==============================] - 0s 2ms/step - loss: 0.5066 - accuracy: 0.7966
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4791 - accuracy: 0.7966
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4568 - accuracy: 0.7966
Epoch 6/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4452 - accuracy: 0.7966
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4393 - accuracy: 0.7966
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4355 - accuracy: 0.7966
Epoch 9/120
249/249 [==============================] - 1s 2ms/step - loss: 0.4334 - accuracy: 0.7966
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4313 - accura

Predictions

Single prediction

In [53]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]]))> 0.5)

1/1 [==============================] - 0s 66ms/step
[[False]]


Predication on testset

In [55]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


Confusion Matrix

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   61]
 [ 223  190]]


0.8569989929506546